### ISSUE TITLE
can you release the tain code?

### ISSUE THREAD

**Issue by water-wave** [aliyun/Self-Evolving-Keypoint-Demo#1]
thanks for your  excellent work , this work was very heuristic. can you release the train code?

**Comment by yoffie** [comment]
Thanks for your attention to our work. We have no plan to release the training code currently. However, we can explain any technical details which the paper has not presented and you want to know.

**Comment by water-wave** [comment]
Thanks ,I learned from your network,and there was no problem during the training.However,the problem of latitude mismatch appeared when the trained network was used to verify the HPatches dataset.can you tell me the problem?

**Comment by yoffie** [comment]
> Thanks ,I learned from your network,and there was no problem during the training.However,the problem of latitude mismatch appeared when the trained network was used to verify the HPatches dataset.can you tell me the problem?

What does latitude mismatch refer to?

**Comment by water-wave** [comment]
When i finished the training phase,the following problem occured when I used the trained model to extract the feature points.the problem is 
RuntimeError: The size of tensor a (711) must match the size of tensor b (712) at non-singleton

**Comment by yoffie** [comment]
> When i finished the training phase,the following problem occured when I used the trained model to extract the feature points.the problem is
> RuntimeError: The size of tensor a (711) must match the size of tensor b (712) at non-singleton

You should carefully check the shape of each layer's output.
