### ISSUE TITLE
resize the hpatch datasets

### ISSUE THREAD

**Issue by water-wave** [aliyun/Self-Evolving-Keypoint-Demo#2]
is Self-Evolving-Keypoint-Demo/utils/resize_imgs.py used to resize the hpatch datases? when I finished the phase of trainning,will I directly use the trained model to verify the resized hpatch datasets?please help me,Thanks.

**Comment by yoffie** [comment]
Yes. we resize images before extract features as some images are too large. Please see line 25-29 in run_all_evaluations.sh.

**Comment by water-wave** [comment]
Thanks for you anwser,I have a question for the ResNet-v2 blocks in the paper,but in you code ,The ResBlock is not same with the ResNet-v2 blocks,in you code ,the ResBlock are BN,Relu ,Conv2d and a shortcut,but the ResNetBlock-v2 are  BN,Relu ,Conv2d, BN,Relu ,Conv2d and a shortcut,please tell me the difference between them.thanks.
