### ISSUE TITLE
About ResNet-v2 

### ISSUE THREAD

**Issue by water-wave** [aliyun/Self-Evolving-Keypoint-Demo#3]
I have a question for the ResNet-v2 blocks in the paper,but in you code ,The ResBlock is not same with the ResNet-v2 blocks,in you code ,the ResBlock are BN,Relu ,Conv2d and a shortcut,but the ResNetBlock-v2 are BN,Relu ,Conv2d, BN,Relu ,Conv2d and a shortcut,please tell me the difference between them.thanks.

**Comment by yoffie** [comment]
The idea of ResNetBlock-v2 is to put the activation layer before the conv layer. So the paper writes we use ResNet-v2 block. We use one combination of BN/Relu/Conv2d in a block to reduce the computation.
