### ISSUE TITLE
export_results.py error

### ISSUE THREAD

**Issue by water-wave** [aliyun/Self-Evolving-Keypoint-Demo#4]
sorry to have been bothering you,but I really want to finish this program.it means a lot to me.I follow the step of run_all_evaluations.sh ,but when I go to the export_results.py,I encountered the problem shown in the follow,please help me,thanks very much.if possible,could you please give me your wechat/QQ?thanks you very much.

Export SEKD local features.
Traceback (most recent call last):
  File "export_results.py", line 40, in <module>
    evaluation.extract_sekd(args)
  File "/home/bob/Self-Evolving-Keypoint-Demo/evaluation/extract_sekd.py", line 35, in extract_sekd
    scores = keypoints[2,:]
IndexError: index 2 is out of bounds for axis 0 with size 2

**Comment by yoffie** [comment]
It seems a bug in nets/sekd.py, please change line 182 to keypoints = keypoints.T. Sorry for the inconvenience.

**Comment by water-wave** [comment]
> It seems a bug in nets/sekd.py, please change line 182 to keypoints = keypoints.T. Sorry for the inconvenience.

**Comment by water-wave** [comment]
thanks for you reply, the above problem has been solved.
but I hava a another question about evaluation dataset,the HPatches sequences dataset ~1.3G and the HPatches patches dataset ~4.2G.Do I need to use one or both?

**Comment by yoffie** [comment]
HPatches sequences dataset(~1.3G) is used to benchmark both detector and descriptor via performing homography estimation. HPatches patches dataset is used to benchmark only the descriptor. It's up to you to select.

**Comment by water-wave** [comment]
thanks very much , One last question ,I wanner uses the program to evaluate R2D2/Superpoint ,How should i do?Thanks you for you patience ,I wish you a happy life and a successful career.

**Comment by yoffie** [comment]
For superpoint, you can refer to 3rd_party/superpoint. For r2d2, you can use https://github.com/naver/r2d2 to extract features and save the results into files (use the same format as sekd). Then you can use this project to calculate and compare the performance quantificationally.

**Comment by water-wave** [comment]
Thanks very very very much,I will follow your steps.Thanks agian.
