### ISSUE TITLE
Descriptor in the network structure is not the original resolution, but a quarter of the original resolution

### ISSUE THREAD

**Issue by hanyunlong233** [aliyun/Self-Evolving-Keypoint-Demo#6]
In your network, descriptors are only generated by a convolution, while not performed upsampling. Therefor, the descriptor is only 1/4 of the original resolution, but that's not how you write it in the article.

**Comment by yoffie** [comment]
We don't upsample the whole feature map but only upsample each keypoint's descriptor for computational efficiency. The implementation can be referred to line 265~271 in nets/sekd.py.
